---
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community1?serverTimezone=Asia/Shanghai
    username: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
server:
  port: 8088
github:
  redirect:
    uri: http://localhost:8088/callback
  client:
    secret: 5adde0e6c06f81c5bd661d915f2555c75ba81520
    id: 8282249c47b5c8ad111e
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.community1.springbootcommunity.mapper
logging:
  level:
    com:
      community1:
        springbootcommunity:
          mapper: debug

#    server.port = 8088
#
#    github.client.id = 8282249c47b5c8ad111e
#    github.client.secret = e5e423c874eaee0fda7d08e4d22fd96258ab4f34
#    github.redirect.uri = http://localhost:8088/callback
#
#    spring.datasource.url=jdbc:mysql://localhost:3306/community1?serverTimezone=Asia/Shanghai
#    spring.datasource.username=root
#    spring.datasource.password=admin
#    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#    spring.flyway.baseline-on-migrate=true
#
#    mybatis.configuration.map-underscore-to-camel-case=true
#    mybatis.type-aliases-package=com.community1.springbootcommunity.mapper
#    mybatis.mapper-locations=classpath:mapper/*.xml
#
#    #thymeleaf
#    #页面热部署设置
#    spring.thymeleaf.cache=false
#    #缓存
#    spring.devtools.restart.enabled=true
#    #开启
#    #spring.devtools.restart.additional-paths=src/main/java
#    #监听目录
#
#    logging.level.com.community1.springbootcommunity.mapper=debug

